### ISSUE TITLE
Cannot read property 'X_ScreenState' of undefined

### ISSUE THREAD

**Issue by Ich-h4lt** [g30r93g/homebridge-panasonic#10]
First of all: Thanks for this new plugin! 
Unfortunately it is not working for me. One Error if opening on macOS with the home app, right click for show control homebridge is crashing:

`TypeError: Cannot read property 'X_ScreenState' of undefined                                
    at Subscription.powerStateSubscription.on (/homebridge/node_modules/homebridge-panasonic-viera-tv/index.js:232:7
3)                                                                                                                  
    at Subscription.emit (events.js:189:13)                                                                         
    at xmlResponseParser (/homebridge/node_modules/node-upnp-subscription/index.js:37:37)                           
    at Parser.<anonymous> (/homebridge/node_modules/xml2js/lib/parser.js:303:18)                                    
    at Parser.emit (events.js:189:13)                                                                               
    at SAXParser.onclosetag (/homebridge/node_modules/xml2js/lib/parser.js:261:26)                                  
    at emit (/homebridge/node_modules/sax/lib/sax.js:624:35)                                                        
    at emitNode (/homebridge/node_modules/sax/lib/sax.js:629:5)                                                     
    at closeTag (/homebridge/node_modules/sax/lib/sax.js:889:7)                                                     
    at SAXParser.write (/homebridge/node_modules/sax/lib/sax.js:1436:13)                                            
    at Parser.exports.Parser.Parser.parseString (/homebridge/node_modules/xml2js/lib/parser.js:322:31)              
    at Parser.parseString (/homebridge/node_modules/xml2js/lib/parser.js:5:59)                                      
    at IncomingMessage.<anonymous> (/homebridge/node_modules/parsexmlresponse/index.js:15:23)                       
    at IncomingMessage.emit (events.js:194:15)                                                                      
    at endReadableNT (_stream_readable.js:1125:12)                                                                  
    at process._tickCallback (internal/process/next_tick.js:63:19)     `

next error:

just any control will lead to power of my tv:

`[5/13/2019, 6:46:08 PM] [TVWohnzimmer] Remote Control Action: 9                                                     
error: connect ECONNREFUSED 192.168.1.25:55000                                                                      
{ Error: connect ECONNREFUSED 192.168.1.25:55000                                                                    
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)                                                 
  errno: 'ECONNREFUSED',                                                                                            
  code: 'ECONNREFUSED',                                                                                             
  syscall: 'connect',                                                                                               
  address: '192.168.1.25',                                                                                          
  port: 55000 }             `

Thanks for your help. If you need further informations, just let me know

**Comment by Ich-h4lt** [comment]
I Adjusted the PowerState function to get more detailed logs. May anyone has an idea:
Code:

`// TV Power
PanasonicTV.prototype.getOn = function(callback) {
    var powerStateSubscription = new UpnpSub(this.HOST, 55000, "/nrc/event_0");

    powerStateSubscription.on("message", (message) => {
    	this.log(message.body);
        let screenState = message.body["e:propertyset"]["e:property"][2]["X_ScreenState"];
        this.log("TV is " + screenState);

        if (screenState === "on") {
        	this.log("screenState on");
            callback(null, true);
        } else {
        	this.log("screenState off");
            callback(null, false);
        }
    });`

LOGS:
`[5/14/2019, 5:54:33 PM] [TVWohnzimmer] { 'e:propertyset':
   { '$': { 'xmlns:e': 'urn:schemas-upnp-org:event-1-0' },
     'e:property': [ [Object], [Object] ] } }
[5/14/2019, 5:54:33 PM] TypeError: Cannot read property 'X_ScreenState' of undefined
    at Subscription.powerStateSubscription.on (/homebridge/node_modules/homebridge-panasonic-viera-tv/index.js:233:73)
    at Subscription.emit (events.js:189:13)
    at xmlResponseParser (/homebridge/node_modules/node-upnp-subscription/index.js:37:37)
    at Parser.<anonymous> (/homebridge/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:189:13)
    at SAXParser.onclosetag (/homebridge/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/homebridge/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/homebridge/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/homebridge/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/homebridge/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/homebridge/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/homebridge/node_modules/xml2js/lib/parser.js:5:59)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/parsexmlresponse/index.js:15:23)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[5/14/2019, 5:54:33 PM] Got SIGTERM, shutting down Homebridge...
`

seems like it did not get the expected power state. also this would explain, that if I control with my iPhone the tv gets shutdown because it is not being considered as on.

**Comment by g30r93g** [comment]
Hi!
I am aware of the issue with the remote and the strange behaviour. I'll dive into that.
The screen state property is inside the `'e:property: [ [Object], [Object] ]`. I should really be matching the response via RegEx (even though its not best practice) and getting the response as such. I'll be adding this to my to do list.

**Comment by g30r93g** [comment]
Hi @Ich-h4lt. Please could you update to 4.5.0 and tell me if your issue persists.

**Comment by Ich-h4lt** [comment]
Thanks for adjusting the code, I will have a look in in in 8 days. I will let you know!

**Comment by Ich-h4lt** [comment]
Hi g30r93g, 

still showing the same issue. How can I assist you in troubleshooting?

Regards,

**Comment by mwj8890** [comment]
any update on this? the state of the TV does not show in the home app, when i try to change input it turns the tv off if it is already on.

**Comment by g30r93g** [comment]
I'm currently working on it. Will hopefully have it fixed by the end of the week.

**Comment by cmicali** [comment]
Accidentally commented on #23 instead of this one.

I am getting the same issue on a TC-P55ST30. All remote control is enabled and manually trying commands with viera.js from the node repl seem to work fine. Note for this TV the POWER command works, but only to turn the set off. It appears the VT/GT models support wake on lan but the ST variants do not.

**Comment by g30r93g** [comment]
I've changed the code for it to account for a null case. Sorry for it taking longer than a week 😄.
Please let me know if this issue persists!

**Comment by cmicali** [comment]
No apologizing, you're working on free & open sw to everyone's benefit! :) Will give it a shot now and report back.

**Comment by cmicali** [comment]
Just FYI - it seems like that problem is resolved, but i'm seeing some strange behavior.

* The NIC in the TV takes a **long** time to come up, so for the first 1-2 minutes the TV is on it's unreachable and status is unreliable.
* The plugin can't seem to get the current TV state - it always shows as off (no error either when TV is reachable)
* If you try to turn the TV on in HomeKit when it's already on the TV turns off (then tile in HomeKit shows as ON)
* In this state, if you turn the TV on and wait until NIC is up, tapping the tile in HomeKit does turn the TV off (expected)

so it seems like
1. Plugin isn't able to query state of TV 
2. The power command is either reversed or it just toggles power state, which desyncs HomeKit state from actual state because of issue 1

**Comment by g30r93g** [comment]
Yes you were right, the plugin wasn’t checking the TV state. Fixed in newest version.

**Comment by Chris-We** [comment]
@g30r93g I'm getting the following errors when starting Homebridge, can you help me?:

`[2020-1-2 20:18:34] TypeError: Cannot read property 'X_ScreenState' of undefined
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at Subscription.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-viera-tv/index.js:288:80)
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at Subscription.emit (events.js:210:5)
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at /usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/node-upnp-subscription/index.js:37:37
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at Parser.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:304:18)
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at Parser.emit (events.js:210:5)
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:262:26)
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at emit (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:624:35)
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at emitNode (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:629:5)
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at closeTag (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:889:7)
Jan 02 20:18:34 raspberrypi4 homebridge[5200]:     at SAXParser.write (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:1436:13)
Jan 02 20:18:34 raspberrypi4 homebridge[5200]: [2020-1-2 20:18:34] Got SIGTERM, shutting down Homebridge...`

System: Raspberry Pi 4 @ raspbian buster
TV: Viera GT30 Series

**Comment by g30r93g** [comment]
I am closing this issue and continuing all relevant communication in issue #32
