### ISSUE TITLE
Since latest update. 

### ISSUE THREAD

**Issue by xeronex** [g30r93g/homebridge-panasonic#27]
since updating the plugin my homebridge crashes with the following message 
TypeError: You entered invalid IP address!
    at new Viera (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/viera.js/viera.js:22:19)
    at PanasonicTV.getServices (/usr/lib/node_modules/homebridge-panasonic-viera-tv/index.js:36:15)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:427:36)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:309:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

All was fine till the update.

**Comment by g30r93g** [comment]
Hi. This has been resolved in 6.2.3.
Carelessly accepted all styling suggestions from Codacy 🙄😂
