### ISSUE TITLE
Crashes homebridge 

### ISSUE THREAD

**Issue by xeronex** [g30r93g/homebridge-panasonic#28]
When I power off the tv I’m get this error 
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at Subscription.powerStateSubscription.on (/usr/lib/node_modules/homebridge-panasonic-viera-tv/index.js:291:13)
    at emitOne (events.js:116:13)
    at Subscription.emit (events.js:211:7)
    at xmlResponseParser (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/node-upnp-subscription/index.js:37:37)
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:306:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/xml2js/lib/parser.js:264:26)
    at emit (/usr/lib/node_modules/homebridge-panasonic-viera-tv/node_modules/sax/lib/sax.js:624:35)
Any ideas?

**Comment by richardbm42uk** [comment]
Having similar issues with HomeBridge crashing whenever this plugin is invoked.

**Comment by GitWonder** [comment]
Me too also

[Homebridge] [28/01/2020, 8:20:36 am] Loading 1 accessories...
[Homebridge] [28/01/2020, 8:20:36 am] [Living Room TV] Initializing Panasonic-TV accessory...
[Homebridge] [28/01/2020, 8:20:36 am] [Living Room TV] Adding Input 1: Name: TV, Type: TV
[Homebridge] [28/01/2020, 8:20:36 am] [Living Room TV] Adding Input 2: Name: Apple TV, Type: HDMI
[Homebridge] [28/01/2020, 8:20:36 am] [Living Room TV] Adding Input 3: Name: Netflix, Type: APPLICATION
[Homebridge] [28/01/2020, 8:20:36 am] [Living Room TV] Initialization complete.
[Homebridge] [28/01/2020, 8:20:36 am] API launched
[Homebridge] [28/01/2020, 8:20:36 am] Service is running on port 51826.
[Homebridge] [28/01/2020, 8:20:52 am] [Living Room TV] TV is off.
[Homebridge] [28/01/2020, 8:46:01 am] [Living Room TV] Powering TV on...
[Homebridge] [28/01/2020, 8:46:18 am] [Living Room TV] Switching to Apple TV
[Homebridge] [28/01/2020, 10:15:49 am] Got SIGINT, shutting down service...

**Comment by g30r93g** [comment]
Hi @xeronex, @rickt42uk, @GitWonder, can you please update to 6.3.0 and tell me if this issue still occurs? Many thanks

**Comment by g30r93g** [comment]
Closing issue due to no reply. Assuming updating to 6.3.0 or higher has fixed this issue. If not, please reopen issue :)
