### ISSUE TITLE
Plugin unresponsive after 1 minute (2013 Viera VT60)

### ISSUE THREAD

**Issue by Moskvitch** [g30r93g/homebridge-panasonic#3]
Accessory shows No response in the Home app
No errors while loading homebridge (normal or debug mode)

Registering accessory 'homebridge-panasonic.Panasonic-TV'
[Panasonic] Initializing Panasonic-TV accessory...

All up to date:
npm@6.9.0
homebridge@0.4.48
homebridge-panasonic-viera-tv@2.0.9

The 2013 Panasonic Viera VT60 series TV is on a static IP address and can be controlled via Panasonic iOS app (except Power ON).

Any ideas? Thanks

UPDATE: Does get added, can control inputs but goes "No response" in about a minute changing the Home app TV button's name to "Other". Restarting homebridge does not help - have to remove homebridge hub and add again.
[2019-4-17 21:51:32] [Panasonic] TV is on
[2019-4-17 21:51:39] [Panasonic] TV is on
[2019-4-17 21:51:48] [Panasonic] TV is on
[2019-4-17 21:51:50] [Panasonic] Switching input to HDMI1
[2019-4-17 21:51:57] [Panasonic] Switching input to TV
[2019-4-17 21:52:02] [Panasonic] TV is on
[2019-4-17 21:52:04] [Panasonic] Switching input to HDMI3
[2019-4-17 21:52:08] [Panasonic] Switching input to HDMI1
[2019-4-17 21:52:18] [Panasonic] Switching input to HDMI2
[2019-4-17 21:52:22] [Panasonic] Switching input to HDMI1
And then the button changes to Other - ! - No response and that's it

**Comment by g30r93g** [comment]
Sorry it hasn't been working. Update to v3.0.0 and tell me if it works. Please make sure you use this version and hopefully it will work well for you!

**Comment by Moskvitch** [comment]
Hi -
Similar problems with the new version.  It does get added, I can switch inputs, then it changes the name of the accessory to Other from Panasonic, and then in about a minute the accessory disappears from Homekit completely.  The icon is just gone!  Have to remove and re-add homebridge to try again.  Also, maybe this matters, when adding the accessory all hdmi inputs are shown in capital letters "HDMI1, HDMI2, TV, PrimeVideo, etc" but when trying to control they change to lowercase "hdmi1, hdmi2, tv, primeVideo..."  No big deal, but maybe this can help identify the problem.
Thanks again for your efforts

**Comment by g30r93g** [comment]
Could you possibly send some screenshots of the issue? It would be greatly appreciated!

**Comment by g30r93g** [comment]
Hi @Moskvitch has the issue since been resolved?

**Comment by Moskvitch** [comment]
Hi -

Unfortunately, not :(

![001a8546-ea08-47a1-bb98-f751e72204c8](https://user-images.githubusercontent.com/11635627/57568222-e603de00-73ec-11e9-94ab-f65e82f7d20f.jpg)
![eabea30e-1b04-4b2d-b2fc-73aab3558c36](https://user-images.githubusercontent.com/11635627/57568223-e603de00-73ec-11e9-9c59-830a7ccf7e85.jpg)

**Comment by Moskvitch** [comment]
Goes "No response" and takes down Homebridge in 1-2 min

running debug=* homebridge-D gives this:

[2019-5-11 13:04:46] Homebridge is running on port 51826.
[2019-5-11 13:04:46] [Panasonic] Error: connect ECONNREFUSED 127.0.0.1:55000

The TV is definitely ON, and for what it's worth the IP address is a static 192.168.1.XX and specified in the config.json as such, not the 127.0.0.1 in the error message

**Comment by g30r93g** [comment]
Hi there. Try version 4.2.9. I had similar issues but I've fixed them on my homebridge. Hopefully the same will be for you.

**Comment by Moskvitch** [comment]
More or less same behaviour with 4.3.1

If the TV is initially Off when homebridge starts, the icon quickly turns to Other/No Response
If it is ON when the plugin is started, then I can control inputs (HDMI1-3/TV)

[2019-5-11 23:19:23] [Panasonic] TV is on
[2019-5-11 23:19:57] [Panasonic] TV is on
[2019-5-11 23:20:26] [Panasonic] Switching to HDMI1
[2019-5-11 23:20:33] [Panasonic] Switching to HDMI2
[2019-5-11 23:20:37] [Panasonic] Switching to HDMI3
[2019-5-11 23:20:43] [Panasonic] Switching to TV
[2019-5-11 23:20:48] [Panasonic] Switching to HDMI1
[2019-5-11 23:21:01] [Panasonic] Powering TV off...
[2019-5-11 23:21:28] [Panasonic] Powering TV on...

Then I turn it on manually using IR remote and I get Other/No response with input names becoming lowercase:

It appears it doesn't;t like it when the TV is off, and it refuses to re-establish connection once it is turned on manually.

**Comment by g30r93g** [comment]
It sounds like it has something to do with the UPnP subscription for the power state. I don't understand the inputs changing to their identifier, very strange.

**Comment by Moskvitch** [comment]
I updated above comment for chronological clarity.  I'll now try to see if it stays connected WITHOUT turning the TV off.

**Comment by Moskvitch** [comment]
Nope.  The TV is ON, I start homebridge, add homebridge and the TV to the Home app, successfully change hdmi 1 / 2 / 3 /TV (managed just one each) and then it goes dead

Other/No response within about one minute



![b2cf18fb-1264-40ad-bc01-7c491249e582](https://user-images.githubusercontent.com/11635627/57574670-fb592680-7445-11e9-9ce2-5fa8f2291d11.jpg)

![be63c8e8-0e8f-40e5-a429-3e8f0587f2d8](https://user-images.githubusercontent.com/11635627/57574671-fe541700-7445-11e9-8e43-700654088b3b.jpg)

![fe2b6e44-d62a-441f-b2c1-16f753b3e621](https://user-images.githubusercontent.com/11635627/57574673-014f0780-7446-11e9-8bbf-24fb59023701.jpg)


![77ef0c23-3493-42c2-8b2b-8ff4f747ab20](https://user-images.githubusercontent.com/11635627/57574675-0613bb80-7446-11e9-8d73-59b50cb403e9.jpg)


![8ce95a3c-7b42-496e-8f49-b84f89c0a005](https://user-images.githubusercontent.com/11635627/57574676-090eac00-7446-11e9-886f-8579c653da6c.jpg)


![753887ca-ca92-49ed-a99a-deb6e26509c7](https://user-images.githubusercontent.com/11635627/57574677-0ca23300-7446-11e9-932c-c143ad2db35f.jpg)

**Comment by Moskvitch** [comment]
debug=* output for this session

[2019-5-11 23:33:17] Homebridge is running on port 51826.
[2019-5-11 23:33:22] [Config] Console v4.4.0 is listening on :: port 8080
[2019-5-11 23:33:40] [Panasonic] TV is on
[2019-5-11 23:33:56] [Panasonic] TV is on
[2019-5-11 23:34:17] [Panasonic] Switching to TV
[2019-5-11 23:34:22] [Panasonic] Switching to HDMI1
[2019-5-11 23:34:26] [Panasonic] Switching to HDMI2
[2019-5-11 23:34:29] [Panasonic] Switching to HDMI3

**Comment by Moskvitch** [comment]
Any other detailed tech logs saved in the debug mode?

**Comment by Moskvitch** [comment]
Hi -

For your WOL support list -

My Panasonic TX-PR65VT60 aka VT60 (EU) Series does NOT support wake-on-lan, the network interface is powered off when the TV is off.

The EU distinction is important as the US version of the same VT60 apparently does support it.

PS Still having the same exact issues with the plugin.  Maybe it’s my network?



Sent from my iPhone

On 11 May 2019, at 23:29, George Nick Gorzynski <notifications@github.com> wrote:

It sounds like it has something to do with the UPnP subscription for the power state. I don't understand the inputs changing to their identifier, very strange.

**Comment by g30r93g** [comment]
Hi @Moskvitch if your TV doesn't support wake on LAN, then you should see a message in 6.2.3 telling you that the TV may not support wake on LAN. Since you already know it isn't supported, please be aware that the TV will always show as on.
As for your issue, it still baffles me as to why it's doing that. Please tell me if the behaviour still exists in 6.2.3.

**Comment by g30r93g** [comment]
Hi @Moskvitch please can you tell me if the plugin still doesn't work in version 6.3.0. I have a bit more free time to try and fix this issue for you.

**Comment by Moskvitch** [comment]
Hi, just tested this:
The previous problems are gone, but there's a new one.
My TV does not support WOL so I turned it on via IR.  Your plugin does not know its on so the button (the icon and the on/off that appears when I long-press the TV accessory icon) stays Off.  I then turn the button on, and then one of these several things happens:
1. The TV turns OFF right away.
2. The button switches to ON, but the input selection buttons do not change anything.
3. The button switches to ON, and after several inout changes, the TV turns OFF.
4. Everything works as expected

I can't quite nail any pattern here.  I make sure the accessory is always in the OFF position, I then turn the TV ON via IR, and then go inside the accessory, turn it to On and start changing inputs.

Hope this helps and thanks again for your efforts

**Comment by Moskvitch** [comment]
This was going on on the pi:

[3/23/2020, 11:49:23 PM] [Viera VT60] Couldn't check power state. Please check your TV's network connection.
[3/23/2020, 11:49:23 PM] [Viera VT60] Alternatively, your TV may not be correctly set up or it may not be able to perform power on from standby.
[3/23/2020, 11:49:38 PM] [Viera VT60] Powering TV on...
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:49:59 PM] [Viera VT60] Switching to TV
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:50:06 PM] [Viera VT60] Powering TV off...
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:50:14 PM] [Viera VT60] Powering TV on...
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:50:20 PM] [Viera VT60] Powering TV off...
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:50:47 PM] [Viera VT60] Powering TV on...
[3/23/2020, 11:50:48 PM] [Viera VT60] Powering TV off...
[3/23/2020, 11:50:49 PM] [Viera VT60] Powering TV on...
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:50:51 PM] [Viera VT60] Powering TV off...
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:51:05 PM] [Viera VT60] Powering TV on...
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:51:10 PM] [Viera VT60] Powering TV off...
error: connect EHOSTUNREACH 192.168.1.60:55000
{ Error: connect EHOSTUNREACH 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:51:12 PM] [Viera VT60] Powering TV on...
[3/23/2020, 11:51:43 PM] [Viera VT60] Powering TV off...
[3/23/2020, 11:52:05 PM] [Viera VT60] Powering TV on...
[3/23/2020, 11:52:13 PM] [Viera VT60] Switching to Receiver
error: read ECONNRESET
{ Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
[3/23/2020, 11:52:17 PM] [Viera VT60] Switching to TV
[3/23/2020, 11:52:19 PM] [Viera VT60] Switching to Receiver
[3/23/2020, 11:52:43 PM] [Viera VT60] Switching to TV
error: read ECONNRESET
{ Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
[3/23/2020, 11:52:52 PM] [Viera VT60] Switching to Receiver
error: read ECONNRESET
{ Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
[3/23/2020, 11:52:56 PM] [Viera VT60] Switching to TV
error: read ECONNRESET
{ Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
[3/23/2020, 11:53:22 PM] [Viera VT60] Switching to Receiver
[3/23/2020, 11:53:46 PM] [Viera VT60] Switching to TV
[3/23/2020, 11:53:57 PM] [Viera VT60] Switching to Receiver
[3/23/2020, 11:54:08 PM] [Viera VT60] Switching to TV
[3/23/2020, 11:54:22 PM] [Viera VT60] Switching to Receiver
[3/23/2020, 11:54:34 PM] [Viera VT60] Switching to TV
[3/23/2020, 11:54:47 PM] [Viera VT60] Switching to Receiver
[3/23/2020, 11:54:59 PM] [Viera VT60] Switching to TV
[3/23/2020, 11:55:10 PM] [Viera VT60] Switching to Receiver
[3/23/2020, 11:55:21 PM] [Viera VT60] Switching to TV
[3/23/2020, 11:55:28 PM] [Viera VT60] Powering TV off...
[3/23/2020, 11:55:38 PM] [Viera VT60] Powering TV on...
error: connect ECONNREFUSED 192.168.1.60:55000
{ Error: connect ECONNREFUSED 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:55:41 PM] [Viera VT60] Powering TV off...
error: connect ECONNREFUSED 192.168.1.60:55000
{ Error: connect ECONNREFUSED 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:56:05 PM] [Viera VT60] Powering TV on...
[3/23/2020, 11:56:32 PM] [Viera VT60] Powering TV off...
error: connect ECONNREFUSED 192.168.1.60:55000
{ Error: connect ECONNREFUSED 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/23/2020, 11:56:48 PM] [Viera VT60] Powering TV on...
[3/23/2020, 11:57:28 PM] [Viera VT60] Switching to Receiver
[3/23/2020, 11:57:33 PM] [Viera VT60] Switching to TV
[3/23/2020, 11:58:30 PM] [Viera VT60] TV is on.
[3/23/2020, 11:58:47 PM] [Viera VT60] Switching to Receiver
[3/23/2020, 11:59:13 PM] [Viera VT60] Switching to TV
[3/23/2020, 11:59:36 PM] [Viera VT60] Switching to Receiver
[3/24/2020, 12:00:00 AM] [Viera VT60] Switching to TV
[3/24/2020, 12:00:53 AM] [Viera VT60] TV is on.
[3/24/2020, 12:01:44 AM] [Viera VT60] TV is on.
[3/24/2020, 12:02:25 AM] [Viera VT60] TV is on.
[3/24/2020, 12:02:53 AM] [Viera VT60] Switching to Receiver
[3/24/2020, 12:03:08 AM] [Viera VT60] Switching to TV
[3/24/2020, 12:03:15 AM] [Viera VT60] Switching to Receiver
[3/24/2020, 12:03:19 AM] [Viera VT60] Switching to TV
[3/24/2020, 12:03:33 AM] [Viera VT60] Switching to Receiver
[3/24/2020, 12:03:37 AM] [Viera VT60] Switching to TV
[3/24/2020, 12:03:39 AM] [Viera VT60] Switching to Receiver
[3/24/2020, 12:03:45 AM] [Viera VT60] Switching to TV
[3/24/2020, 12:03:49 AM] [Viera VT60] Powering TV off...
[3/24/2020, 12:04:13 AM] [Viera VT60] Powering TV on...
[3/24/2020, 12:04:26 AM] [Viera VT60] Switching to Receiver
error: connect ECONNREFUSED 192.168.1.60:55000
{ Error: connect ECONNREFUSED 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/24/2020, 12:04:28 AM] [Viera VT60] Powering TV off...
error: connect ECONNREFUSED 192.168.1.60:55000
{ Error: connect ECONNREFUSED 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }
[3/24/2020, 12:04:44 AM] [Viera VT60] Powering TV on...
[3/24/2020, 12:04:52 AM] [Viera VT60] Switching to TV
[3/24/2020, 12:05:08 AM] [Viera VT60] Powering TV off...
error: connect ECONNREFUSED 192.168.1.60:55000
{ Error: connect ECONNREFUSED 192.168.1.60:55000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 55000 }

**Comment by 19kirk79** [comment]
> 
> 
> Hi, just tested this:
> The previous problems are gone, but there's a new one.
> My TV does not support WOL so I turned it on via IR. Your plugin does not know its on so the button (the icon and the on/off that appears when I long-press the TV accessory icon) stays Off. I then turn the button on, and then one of these several things happens:
> 
>     1. The TV turns OFF right away.
> 
>     2. The button switches to ON, but the input selection buttons do not change anything.
> 
>     3. The button switches to ON, and after several inout changes, the TV turns OFF.
> 
>     4. Everything works as expected
> 
> 
> I can't quite nail any pattern here. I make sure the accessory is always in the OFF position, I then turn the TV ON via IR, and then go inside the accessory, turn it to On and start changing inputs.
> 
> Hope this helps and thanks again for your efforts

I´ve got a ZT60 (EU) and exactly the same problem.
