### ISSUE TITLE
Homebridge Crash

### ISSUE THREAD

**Issue by ValoV83** [g30r93g/homebridge-panasonic#39]
I've had one or two crashes lately when switching the TV off from within the Home app. This results in Homebridge crashing and needing to be restarted.

Log of the crash:

15/05/2020, 08:21:52 [TX-42AS650B] X_ScreenState: on
15/05/2020, 08:21:56 [TX-42AS650B] X_ScreenState: on
15/05/2020, 08:21:56 [TX-42AS650B] Powering TV off...
15/05/2020, 08:21:56 [TX-42AS650B] Unsuccessful communication with TV.
15/05/2020, 08:21:56 Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:11:19
    at Subscription.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-panasonic-viera-tv/index.js:259:13)
    at Subscription.emit (events.js:310:20)
    at /home/hoobs/.hoobs/node_modules/node-upnp-subscription/index.js:37:37
    at Parser.<anonymous> (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:310:20)
    at SAXParser.onclosetag (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:889:7)
15/05/2020, 08:21:56 Got SIGTERM, shutting down Bridge...

Panasonic Viera Tv Plugin: v7.2.0
HOOBS versions: 3.2.3 , 3.2.4 , 3.2.6

**Comment by ValoV83** [comment]
Any update on a fix for this issue? It’s becoming a real pain as pretty much every time I use the plugin to control my TV it’s crashing the Homebridge Service on HOOBS and I need to manually restart the Homebridge service on my HOOBS box.
